sudo: required

services:
  - docker

before_install:
  - docker build -t vertx-grpc .

install:
  - docker run --rm -v $(pwd):/workdir:Z -e CROSS_TRIPLE=${CROSS_TRIPLE} -it vertx-grpc ./build-protobuf.sh

script:
  - docker run --rm -v $(pwd):/workdir:Z -e CROSS_TRIPLE=${CROSS_TRIPLE} -it vertx-grpc make

env:
  - CROSS_TRIPLE=x86_64-linux-gnu
  - CROSS_TRIPLE=i686-w64-mingw32
  - CROSS_TRIPLE=x86_64-w64-mingw32
  - CROSS_TRIPLE=x86_64-apple-darwin
