sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - mkdir -p target
  - docker build -t vertx-grpc .

cache:
  directories:
  - target/x86_64-linux-gnu/protobuf-3.1.0
  - target/i686-w64-mingw32/protobuf-3.1.0
  - target/x86_64-w64-mingw32/protobuf-3.1.0
  - target/x86_64-apple-darwin14/protobuf-3.1.0

install:
  - docker run --rm -v $(pwd):/workdir:Z -e CROSS_TRIPLE=x86_64-linux-gnu -it vertx-grpc ./scripts/build-protobuf.sh
  - docker run --rm -v $(pwd):/workdir:Z -e CROSS_TRIPLE=i686-w64-mingw32 -it vertx-grpc ./scripts/build-protobuf.sh
  - docker run --rm -v $(pwd):/workdir:Z -e CROSS_TRIPLE=x86_64-w64-mingw32 -it vertx-grpc ./scripts/build-protobuf.sh
  - docker run --rm -v $(pwd):/workdir:Z -e CROSS_TRIPLE=x86_64-apple-darwin -it vertx-grpc ./scripts/build-protobuf.sh

script:
  - docker run --rm -v $(pwd):/workdir:Z -e CROSS_TRIPLE=x86_64-linux-gnu -it vertx-grpc make
  - docker run --rm -v $(pwd):/workdir:Z -e CROSS_TRIPLE=i686-w64-mingw32 -it vertx-grpc make
  - docker run --rm -v $(pwd):/workdir:Z -e CROSS_TRIPLE=x86_64-w64-mingw32 -it vertx-grpc make
  - docker run --rm -v $(pwd):/workdir:Z -e CROSS_TRIPLE=x86_64-apple-darwin -it vertx-grpc make

after_success:
  if [[ "$(mvn org.apache.maven.plugins:maven-help-plugin:evaluate -Dexpression=project.version -B | grep -v '\[')" =~ .*SNAPSHOT ]] && [[ "${TRAVIS_BRANCH}" = "master" ]] && [[ "${TRAVIS_PULL_REQUEST}" = "false" ]]; then
    mvn deploy -Dmaven.test.skip=true;
  fi

env:
  global:
    - secure: IjdignAqTlY9dvkCF4Z1tHyILrFBou+CoizRlS8L43B/vwTnZEEAgyfXG7zAkT1khje9c+TOqkEYWv+24VTgaX3mkgE1Am6nhqxYIG6ULdVVRJT5JAb8L//F3Sm+g/sS5guesUjT1wkEQ8ew6ZQ7/JoC/WKjqT7jklsX5g/6UsE=
    - secure: jGsaoOfcLzrHgsfIJBLTnhxO6C+4+qRYRMsLG1oJY4DfPZOqa78ShrL50kns15WDt9PkVq4ddPfINJrA5PmN3e0evupPRRDh1mcbvDjK9d4Mldyl5IJxRKL2lvPenC+EujOegVr9jp7Jv6QwI9mc4SJjzwA65uB96K5zvbEmUF0=
